---
- name: Comment swap in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'
  register: fstab_swap

- name: Disable swap for current session
  ansible.builtin.shell: |
    swapoff -a
  when: (fstab_swap.changed) or (ansible_facts.swaptotal_mb != 0)

- name: Generate /etc/modules-load.d/k8s.conf for br_netfilter module's persistence
  ansible.builtin.template:
    src: modules-load.d/k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf

- name: Load the br_netfilter module for current session
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Activate kernel parameters
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/k8s.conf
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: Ensure that some necessary packages are installed
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - conntrack
    - socat
    - iproute-tc
    - git
  when: ansible_facts.distribution == 'Rocky'

- name: Stop and disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Install kubernetes python library
  pip:
    name: kubernetes
  when: "'controlplane' in group_names"