- name: Local download kubeadm
  include: tasks/download.yaml
  vars:
    src: https://storage.googleapis.com/kubernetes-release/release/v1.23.5/bin/linux/amd64/kubeadm
    checksum: https://storage.googleapis.com/kubernetes-release/release/v1.23.5/bin/linux/amd64/kubeadm.sha256
    hash_type: sha256
    dest: /tmp/kubeadm
    mode: '0744'
  run_once: true
  delegate_to: localhost

- name: Copy kubeadm to /usr/local/bin
  ansible.builtin.copy:
    src: "{{ file_info.dest }}"
    dest: /usr/local/bin
    mode: '0755'

- name: Local download kubectl
  include: tasks/download.yaml
  vars:
    src: https://storage.googleapis.com/kubernetes-release/release/v1.23.5/bin/linux/amd64/kubectl
    checksum: https://storage.googleapis.com/kubernetes-release/release/v1.23.5/bin/linux/amd64/kubectl.sha256
    hash_type: sha256
    dest: /tmp/kubectl
    mode: '0744'
  run_once: true
  delegate_to: localhost

- name: Copy kubectl to /usr/local/bin
  ansible.builtin.copy:
    src: "{{ file_info.dest }}"
    dest: /usr/local/bin
    mode: '0755'
  when: "'controlplane' in group_names"

- name: Check if kubectl autocompletion enabled
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source <(kubectl completion bash)"
  check_mode: yes
  register: kubectl_completion
  when: "'controlplane' in group_names"

- name: Enable kubectl autocompletion
  ansible.builtin.shell: |
    echo 'source <(kubectl completion bash)' >>~/.bashrc
  when: kubectl_completion.changed == true

- name: Local download kubelet
  include: tasks/download.yaml
  vars:
    src: https://storage.googleapis.com/kubernetes-release/release/v1.23.5/bin/linux/amd64/kubelet
    checksum: https://storage.googleapis.com/kubernetes-release/release/v1.23.5/bin/linux/amd64/kubelet.sha256
    hash_type: sha256
    dest: /tmp/kubelet
    mode: '0744'
  run_once: true
  delegate_to: localhost

- name: Copy kubelet to /usr/local/bin
  ansible.builtin.copy:
    src: "{{ file_info.dest }}"
    dest: /usr/local/bin
    mode: '0755'

- name: Generate systemd unit config for kubelet (1 of 2)
  ansible.builtin.template:
    src: systemd/kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service

- name: Create a directory /etc/systemd/system/kubelet.service.d if it does not exist
  ansible.builtin.file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    mode: '0755'

- name: Generate systemd unit config for kubelet (2 of 2)
  ansible.builtin.template:
    src: systemd/10-kubeadm.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: Reload systemd manager configuration and enable kubelet service
  ansible.builtin.systemd:
    enabled: yes
    daemon_reload: yes
    name: kubelet

- name: Local download helm
  include: tasks/download.yaml
  vars:
    src: https://get.helm.sh/helm-v3.8.1-linux-amd64.tar.gz
    checksum: https://get.helm.sh/helm-v3.8.1-linux-amd64.tar.gz.sha256sum
    hash_type: sha256
    dest: /tmp/helm-v3.8.1-linux-amd64.tar.gz
    mode: '0744'
  run_once: true
  delegate_to: localhost 

- name: Unarchive helm package
  ansible.builtin.unarchive:
    src: "{{ file_info.dest }}"
    dest: /tmp/
  run_once: true
  delegate_to: localhost 

- name: Copy helm to controlplane nodes
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin
    mode: '0755'
  when: "'controlplane' in group_names"

- name: Check if helm autocompletion enabled
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source <(helm completion bash)"
  check_mode: yes
  register: helm_completion
  when: "'controlplane' in group_names"

- name: Enable helm autocompletion
  ansible.builtin.shell: |
    echo 'source <(helm completion bash)' >>~/.bashrc
  when: helm_completion.changed == true

- name: Install Helm env plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present
  when: "'controlplane' in group_names"