- name: Install kubernetes python library
  pip:
    name: kubernetes

- name: Deploy Flannel CNI plugin
  kubernetes.core.k8s:
    state: present
    template: manifests/kube-flannel.yml.j2
  when: cni_plugin == 'flannel'

- name: Deploy Calico CNI plugin
  kubernetes.core.k8s:
    state: present
    template: manifests/calico.yml.j2
  when: cni_plugin == 'calico'