- name: Get checksum
  uri:
    url: '{{ checksum }}'
    return_content: yes
  register: file_checksum

- name: Download {{ src }}
  get_url:
    url: '{{ src }}'
    dest: '{{ dest }}'
    mode: '{{ mode }}'
    checksum: '{{ hash_type }}:{{ file_checksum.content.split(" ")[0] }}'
  register: file_info