---
- name: Create a directory /etc/kubernetes/manifests if it does not exist
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: '0755'

- name: Generate kube-vip Pod manifest
  ansible.builtin.template:
    src: manifests/kube-vip.yaml.j2
    dest: /etc/kubernetes/manifests/kube-vip.yaml