- name: Add metallb helm repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"
  no_log: true

- name: Deploy metallb helm chart
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb
    create_namespace: true
    wait: yes
    values: "{{ lookup('template', 'templates/helm_chart_values/metallb.yaml.j2') | from_yaml }}"
  run_once: true