- name: Add traefik helm repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://helm.traefik.io/traefik"
  no_log: true

- name: Deploy traefik helm chart
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    create_namespace: true
    wait: yes
    # values: "{{ lookup('template', 'templates/helm_chart_values/kube-prometheus-stack.yml.j2') | from_yaml }}"
  run_once: true